# Generated by Django 3.0 on 2023-03-23 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='productimage/%Y/%m/%d/%H/%M/%S', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
